# Generated by Django 5.2.8 on 2026-01-13 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Insumo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Pago (R$)')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Quantidade na Embalagem')),
                ('unit', models.CharField(choices=[('g', 'Gramas (g)'), ('ml', 'Mililitros (ml)'), ('un', 'Unidades (un)')], default='g', max_length=5, verbose_name='Unidade')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_weight_g', models.DecimalField(decimal_places=2, default=0, help_text='Peso de cada unidade (só o doce) em gramas', max_digits=6, verbose_name='Peso Unitário (g)')),
                ('evaporation_percent', models.IntegerField(default=15, help_text='Perda de peso no cozimento (%)', verbose_name='Perda %')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batch_recipe', to='produtos.product', verbose_name='Produto')),
            ],
        ),
        migrations.CreateModel(
            name='BatchIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Qtd. Usada')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='produtos.productbatch')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.supply', verbose_name='Insumo')),
            ],
        ),
    ]
