# Generated by Django 5.2.8 on 2026-01-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_supply_productbatch_batchingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Estoque (Qtd Embalagens)'),
        ),
    ]
