# Generated by Django 5.2.8 on 2026-01-20 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0006_supply_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productbatch',
            name='evaporation_percent',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='batch_recipe', to='produtos.product'),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='unit_weight_g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
