# Generated by Django 6.0.2 on 2026-02-22 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0007_alter_productbatch_evaporation_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='customizable_slots',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade de Itens'),
        ),
        migrations.AddField(
            model_name='product',
            name='customization_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customization_for', to='produtos.category', verbose_name='Categoria de Itens'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_customizable',
            field=models.BooleanField(default=False, verbose_name='É personalizável?'),
        ),
    ]
