# Generated by Django 6.0.3 on 2026-03-14 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0008_product_customizable_slots_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='produtos.product')),
                ('sub_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contained_in_bundles', to='produtos.product')),
            ],
        ),
    ]
