# Generated by Django 6.0.2 on 2026-02-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
