# Generated by Django 5.2.8 on 2025-12-27 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_order_coupon_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Limite de Usos'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_purchase',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Mínimo'),
        ),
        migrations.AddField(
            model_name='coupon',
            name='used_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade Usada'),
        ),
    ]
