# Generated by Django 5.2.8 on 2025-12-30 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_coupon_max_uses_coupon_min_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mercado_pago_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='mercado_pago_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
