# Generated by Django 6.0.2 on 2026-02-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_order_mercado_pago_id_order_mercado_pago_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
