# Generated by Django 6.0.2 on 2026-02-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0010_orderitem_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observações do Pedido'),
        ),
    ]
