# Generated by Django 6.0.2 on 2026-02-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_order_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('preparing', 'Em Produção'), ('shipped', 'Enviado'), ('delivered', 'Entregue'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20),
        ),
    ]
