# Generated by Django 6.0.3 on 2026-04-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(max_length=50, unique=True, verbose_name='ID do Cartão')),
                ('customer_name', models.CharField(blank=True, max_length=100, verbose_name='Nome do Cliente')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('stamps', models.PositiveIntegerField(default=0, verbose_name='Quantidade de Selos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
