# Generated by Django 6.0.3 on 2026-04-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidelidade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltycard',
            name='stamp_positions',
            field=models.JSONField(blank=True, default=list, verbose_name='Posições Visuais'),
        ),
    ]
