# Generated by Django 6.0.3 on 2026-04-04 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fidelidade', '0002_loyaltycard_stamp_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltycard',
            name='stamp_positions',
            field=models.TextField(default='[]', verbose_name='Posições dos Selos (JSON)'),
        ),
    ]
