# Generated by Django 6.0.2 on 2026-02-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='topic',
            field=models.CharField(default='Assunto Geral', max_length=100),
        ),
    ]
