# Generated by Django 5.2.8 on 2025-12-24 03:34

import usuarios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Obrigatório. 150 caracteres ou menos. Letras, números e @/./+/-/_/espaços.', max_length=150, unique=True, validators=[usuarios.models.SpaceUnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
