# Generated by Django 5.2.8 on 2025-12-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='about_photo',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
