# Generated by Django 5.2.8 on 2025-12-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_storesettings_about_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='delivery_notice',
            field=models.TextField(default='Não realizamos entregas no momento. Apenas retirada.', verbose_name='Aviso de Entrega / Localização'),
        ),
    ]
