# Generated by Django 5.2.8 on 2025-12-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_storesettings_delivery_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='delivery_details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes da Localização'),
        ),
    ]
