# Generated by Django 5.2.8 on 2025-12-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0004_storesettings_delivery_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('date', models.DateField(verbose_name='Data da Despesa')),
                ('category', models.CharField(choices=[('fixed', 'Custo Fixo'), ('variable', 'Custo Variável'), ('stock', 'Reposição de Estoque'), ('marketing', 'Marketing'), ('other', 'Outros')], default='other', max_length=20, verbose_name='Categoria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Meta')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Alvo')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Atual')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Meta Financeira',
                'verbose_name_plural': 'Metas Financeiras',
                'ordering': ('deadline',),
            },
        ),
    ]
