# Generated by Django 5.2.8 on 2025-12-26 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_expense_financialgoal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='FinancialGoal',
        ),
    ]
