# Generated by Django 5.2.8 on 2025-12-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_delete_expense_delete_financialgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='gps_enabled',
            field=models.BooleanField(default=False, verbose_name='Rastreamento em Tempo Real'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='last_gps_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
