# Generated by Django 5.2.8 on 2025-12-31 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_storesettings_gps_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='cash_in_drawer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Dinheiro em Gaveta'),
        ),
    ]
