# Generated by Django 5.2.8 on 2025-12-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_storesettings_cash_in_drawer'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='cash_breakdown',
            field=models.JSONField(blank=True, default=dict, verbose_name='Detalhamento das Notas'),
        ),
    ]
