# Generated by Django 5.2.8 on 2026-01-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0009_storesettings_cash_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='pix_key',
            field=models.CharField(default='81983964906', max_length=255, verbose_name='Chave Pix Manual'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='pix_manual_enabled',
            field=models.BooleanField(default=False, verbose_name='Pix Manual (Estático)'),
        ),
    ]
