# Generated by Django 6.0.2 on 2026-02-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0011_alter_storesettings_pix_key_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='mp_access_token_fabio',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token Pix Fabio (MP)'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='mp_access_token_yasmim',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Token Pix Yasmim (MP)'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='mp_active_account',
            field=models.CharField(choices=[('fabio', 'Fabio'), ('yasmim', 'Yasmim')], default='fabio', max_length=10, verbose_name='Conta Pix Ativa (MP)'),
        ),
    ]
